<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BelgiumPulse.Domain\BelgiumPulse.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="AirQuality\Queries\GetAirQualityMeasurements\" />
    <Folder Include="Stib\Commands\ReportDisruption\" />
    <Folder Include="Stib\Queries\GetAllStibLines\" />
    <Folder Include="Stib\Queries\GetStibLineByNumber\" />
    <Folder Include="Weather\Queries\GetActiveWeatherAlerts\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
