// <auto-generated />
using System;
using BelgiumPulse.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BelgiumPulse.Infrastructure.Migrations
{
    [DbContext(typeof(BelgiumPulseDbContext))]
    partial class BelgiumPulseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BelgiumPulse.Domain.Entities.AirQualityMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Index")
                        .HasColumnType("int")
                        .HasColumnName("AqiValue");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("NO2")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("NO2");

                    b.Property<decimal>("PM10")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("PM10");

                    b.Property<decimal>("PM25")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("PM25");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Municipality");

                    b.HasIndex("StationName", "MeasuredAt");

                    b.ToTable("AirQualityMeasurements", (string)null);
                });

            modelBuilder.Entity("BelgiumPulse.Domain.Entities.StibLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisruptionMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsOperational")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LineNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LineNumber")
                        .IsUnique();

                    b.ToTable("StibLines", (string)null);
                });

            modelBuilder.Entity("BelgiumPulse.Domain.Entities.UserAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("AlertType", "TargetId", "IsActive");

                    b.ToTable("UserAlerts", (string)null);
                });

            modelBuilder.Entity("BelgiumPulse.Domain.Entities.WeatherAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Region");

                    b.HasIndex("ValidFrom", "ValidUntil");

                    b.ToTable("WeatherAlerts", (string)null);
                });

            modelBuilder.Entity("BelgiumPulse.Domain.Entities.AirQualityMeasurement", b =>
                {
                    b.OwnsOne("BelgiumPulse.Domain.ValueObjects.Coordinates", "Location", b1 =>
                        {
                            b1.Property<Guid>("AirQualityMeasurementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Latitude")
                                .HasColumnType("decimal(10,7)")
                                .HasColumnName("Latitude");

                            b1.Property<decimal>("Longitude")
                                .HasColumnType("decimal(10,7)")
                                .HasColumnName("Longitude");

                            b1.HasKey("AirQualityMeasurementId");

                            b1.ToTable("AirQualityMeasurements");

                            b1.WithOwner()
                                .HasForeignKey("AirQualityMeasurementId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("BelgiumPulse.Domain.Entities.StibLine", b =>
                {
                    b.OwnsOne("BelgiumPulse.Domain.ValueObjects.Coordinates", "CurrentPosition", b1 =>
                        {
                            b1.Property<Guid>("StibLineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Latitude")
                                .HasColumnType("decimal(10,7)")
                                .HasColumnName("Latitude");

                            b1.Property<decimal>("Longitude")
                                .HasColumnType("decimal(10,7)")
                                .HasColumnName("Longitude");

                            b1.HasKey("StibLineId");

                            b1.ToTable("StibLines");

                            b1.WithOwner()
                                .HasForeignKey("StibLineId");
                        });

                    b.Navigation("CurrentPosition");
                });

            modelBuilder.Entity("BelgiumPulse.Domain.Entities.WeatherAlert", b =>
                {
                    b.OwnsOne("BelgiumPulse.Domain.ValueObjects.Coordinates", "Location", b1 =>
                        {
                            b1.Property<Guid>("WeatherAlertId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Latitude")
                                .HasColumnType("decimal(10,7)")
                                .HasColumnName("Latitude");

                            b1.Property<decimal>("Longitude")
                                .HasColumnType("decimal(10,7)")
                                .HasColumnName("Longitude");

                            b1.HasKey("WeatherAlertId");

                            b1.ToTable("WeatherAlerts");

                            b1.WithOwner()
                                .HasForeignKey("WeatherAlertId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
